name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Dependencies
        run: |
          yarn install --immutable
          yarn playwright install --with-deps firefox

      - name: Build with tsc
        run: yarn build

      - name: Publish Package
        run: |
          yarn config set -H "npmAuthToken" ${NPM_TOKEN}
          yarn npm publish --verbose
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
