name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: yarn

      - name: Install Dependencies
        run: |
          yarn install --immutable
          yarn playwright install --with-deps firefox

      - name: Test with Vitest
        run: yarn test:run
        env:
          CI: true
