name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build with tsc
        run: yarn build

      - name: Test with Vitest
        run: yarn test:run
        env:
          CI: true
