name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build with tsc
        run: yarn build

      - name: Test with Jest
        run: yarn test
        env:
          CI: true
