name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: pnpm

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm exec playwright install --with-deps firefox

      - name: Test with Vitest
        run: pnpm test:run
        env:
          CI: true
